# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nginx_controller_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dnginx_controller_server.proto\x12\x17nginx_controller_server\"+\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"#\n\x0fMessageResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x32\x65\n\x0b\x41gentNotify\x12V\n\x06notify\x12 .nginx_controller_server.Message\x1a(.nginx_controller_server.MessageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nginx_controller_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=58
  _MESSAGE._serialized_end=101
  _MESSAGERESPONSE._serialized_start=103
  _MESSAGERESPONSE._serialized_end=138
  _AGENTNOTIFY._serialized_start=140
  _AGENTNOTIFY._serialized_end=241
# @@protoc_insertion_point(module_scope)
